package engine.rules.scmp.enums;

public enum RuleAction_deprecated {
    GENERATE_PACKING_SLIP_FOR_SHIPPING,
    DUPLICATE_PACKING_SLIP_FOR_ROYALTY_DEPARTMENT,
    GENERATE_COMMISSION_PAYMENT_TO_AGENT,
    EMAIL_TO_OWNER,
    ACTIVATE_MEMBERSHIP,
    UPGRADE_MEMBERSHIP,
    ADD_FREE_FIRST_AID_VIDEO
}
